Presupuestador/Presupuestador/Models/Plantilla.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presupuestador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plantilla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plantilla()
        {
            this.Plantillas_Tareas = new HashSet<Plantillas_Tareas>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantillas_Tareas> Plantillas_Tareas { get; set; }
    }
}

Presupuestador/Presupuestador/Models/Tarea.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presupuestador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarea()
        {
            this.Presupuestos_Tareas = new HashSet<Presupuestos_Tareas>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presupuestos_Tareas> Presupuestos_Tareas { get; set; }
    }
}

Presupuestador/Presupuestador/ViewModels/PlantillaViewModel.cs
using System;
using System.Collections.Generic;

namespace Presupuestador.ViewModels
{
  public class PlantillaViewModel
  {
    public int id { get; set; }
    public string nombre { get; set; }
    public int tarea_id { get; set; }
    public List<TareaViewModel> TareasAsignadas { get; set; } = new List<TareaViewModel>();
  }
}

Presupuestador/Presupuestador/ViewModels/Tarea.cs
namespace Presupuestador.ViewModels
{
  public class Tarea
  {
    public int TareaId { get; set; }

    public string Descripcion { get; set; }

    public int RecursoId { get; set; }

    public string Recurso { get; set; }

    public string Rol { get; set; }

    public string Rango { get; set; }

    public int Tiempo { get; set; }
  }
}

Presupuestador/Presupuestador/ViewModels/TareaViewModel.cs
namespace Presupuestador.ViewModels
{
  public class TareaViewModel
  {
    public int TareaId { get; set; }

    public string Descripcion { get; set; }

    public int RecursoId { get; set; }

    public string Recurso { get; set; }

    public string Rol { get; set; }

    public string Rango { get; set; }

    public int Tiempo { get; set; }
  }
}

Presupuestador/Presupuestador/Controllers/PlantillasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Presupuestador.Models;
using Presupuestador.ViewModels;

namespace Presupuestador.Controllers
{
    public class PlantillasController : Controller
    {
        private Entities1 db = new Entities1();

        // GET: Plantillas
        public ActionResult Index()
        {
            return View(db.Plantillas.ToList());
        }

        // GET: Plantillas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plantilla plantilla = db.Plantillas.Find(id);
            if (plantilla == null)
            {
                return HttpNotFound();
            }
            return View(plantilla);
        }

        // GET: Plantillas/Create
        public ActionResult Create()
        {
            ViewBag.tarea_id = new SelectList(db.Tareas, "id", "titulo");
            PlantillaViewModel presupuesto = new PlantillaViewModel();
            return View(presupuesto);
        }

        // POST: Plantillas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PlantillaViewModel plantillaViewModel)
        {
            if (ModelState.IsValid)
            {
                Plantilla plantilla = new Plantilla()
                {
                    nombre = plantillaViewModel.nombre
                };
                db.Plantillas.Add(plantilla);
                db.SaveChanges();

                foreach (var tarea in plantillaViewModel.TareasAsignadas)
                {
                    Plantillas_Tareas plantillas_Tareas = new Plantillas_Tareas()
                    {
                        plantilla_id = plantilla.id,
                        tarea_id = tarea.TareaId
                    };
                    db.Plantillas_Tareas.Add(plantillas_Tareas);
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(plantillaViewModel);
        }

        // GET: Plantillas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plantilla plantilla = db.Plantillas.Find(id);
            if (plantilla == null)
            {
                return HttpNotFound();
            }

            List<Plantillas_Tareas> tareasAsignadas = db.Plantillas_Tareas.Where(x => x.plantilla_id == id.Value).ToList();

            List<TareaViewModel> tareasViewModel = new List<TareaViewModel>();
            foreach(var tarea in tareasAsignadas)
            {
                tareasViewModel.Add(new TareaViewModel()
                {
                    Descripcion = tarea.Tarea.titulo,
                    TareaId = tarea.tarea_id
                });
            }

            PlantillaViewModel plantillaViewModel = new PlantillaViewModel()
            {
                id = id.Value,
                nombre = plantilla.nombre,
                TareasAsignadas = tareasViewModel
            };

            ViewBag.tarea_id = new SelectList(db.Tareas, "id", "titulo");
            return View(plantillaViewModel);
        }

        // POST: Plantillas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PlantillaViewModel plantillaViewModel)
        {
            if (ModelState.IsValid)
            {
                Plantilla plantilla = db.Plantillas.Find(plantillaViewModel.id);
                plantilla.nombre = plantillaViewModel.nombre;

                var plantillas_tareas = db.Plantillas_Tareas.Where(x => x.plantilla_id == plantilla.id).ToList();
                foreach(var plantilla_tarea in plantillas_tareas)
                {
                    db.Plantillas_Tareas.Remove(plantilla_tarea);
                }
                db.SaveChanges();
                foreach (var tarea in plantillaViewModel.TareasAsignadas)
                {
                    if(tarea.TareaId != 0) { 
                        Plantillas_Tareas plantillas_Tareas = new Plantillas_Tareas()
                        {
                            plantilla_id = plantilla.id,
                            tarea_id = tarea.TareaId
                        };
                        db.Plantillas_Tareas.Add(plantillas_Tareas);
                    }
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(plantillaViewModel);
        }

        // GET: Plantillas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plantilla plantilla = db.Plantillas.Find(id);
            if (plantilla == null)
            {
                return HttpNotFound();
            }
            return View(plantilla);
        }

        // POST: Plantillas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var plantillas_tareas = db.Plantillas_Tareas.Where(x => x.plantilla_id == id).ToList();
            foreach (var plantilla_tarea in plantillas_tareas)
            {
                db.Plantillas_Tareas.Remove(plantilla_tarea);
            }
            Plantilla plantilla = db.Plantillas.Find(id);
            db.Plantillas.Remove(plantilla);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public PartialViewResult AgregarTarea(int tareaId, string tareaTitulo)
        {
            TareaViewModel tarea = new TareaViewModel
            {
                TareaId = tareaId,
                Descripcion = tareaTitulo
            };
            return PartialView("_Tareas", tarea);
        }
    }
}

Presupuestador/Presupuestador/Controllers/TareasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Presupuestador.Models;

namespace Presupuestador.Controllers
{
    public class TareasController : Controller
    {
        private Entities1 db = new Entities1();

        // GET: Tareas
        public ActionResult Index()
        {
            var tareas = db.Tareas.Include(t => t.Categoria).Include(t => t.Tipos_Tareas);
            return View(tareas.ToList());
        }

        // GET: Tareas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarea tarea = db.Tareas.Find(id);
            if (tarea == null)
            {
                return HttpNotFound();
            }
            return View(tarea);
        }

        // GET: Tareas/Create
        public ActionResult Create()
        {
            ViewBag.categoria_id = new SelectList(db.Categorias, "id", "descripcion");
            ViewBag.tipo_tarea_id = new SelectList(db.Tipos_Tareas, "id", "descripcion");
            return View();
        }

        // POST: Tareas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,titulo,descripcion,tipo_tarea_id,categoria_id")] Tarea tarea)
        {
            if (ModelState.IsValid)
            {
                db.Tareas.Add(tarea);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.categoria_id = new SelectList(db.Categorias, "id", "descripcion", tarea.categoria_id);
            ViewBag.tipo_tarea_id = new SelectList(db.Tipos_Tareas, "id", "descripcion", tarea.tipo_tarea_id);
            return View(tarea);
        }

        // GET: Tareas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarea tarea = db.Tareas.Find(id);
            if (tarea == null)
            {
                return HttpNotFound();
            }
            ViewBag.categoria_id = new SelectList(db.Categorias, "id", "descripcion", tarea.categoria_id);
            ViewBag.tipo_tarea_id = new SelectList(db.Tipos_Tareas, "id", "descripcion", tarea.tipo_tarea_id);
            return View(tarea);
        }

        // POST: Tareas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,titulo,descripcion,tipo_tarea_id,categoria_id")] Tarea tarea)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tarea).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.categoria_id = new SelectList(db.Categorias, "id", "descripcion", tarea.categoria_id);
            ViewBag.tipo_tarea_id = new SelectList(db.Tipos_Tareas, "id", "descripcion", tarea.tipo_tarea_id);
            return View(tarea);
        }

        // GET: Tareas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarea tarea = db.Tareas.Find(id);
            if (tarea == null)
            {
                return HttpNotFound();
            }
            return View(tarea);
        }

        // POST: Tareas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tarea tarea = db.Tareas.Find(id);
            db.Tareas.Remove(tarea);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Presupuestador/Presupuestador/Views/Plantillas/Create.cshtml
@model Presupuestador.ViewModels.PlantillaViewModel

@{
    ViewBag.Title = "Crear Plantilla";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear Plantilla</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

        <hr />
        <div class="form-row">
            <div class="form-group col-sm-4">
                @Html.LabelFor(model => model.nombre, "Nombre", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>

            <div class="form-group col-sm-4">
                @Html.LabelFor(model => model.tarea_id, "Tareas", new { @class = "control-label" })
                @Html.DropDownList("tarea_id", null, htmlAttributes: new { @class = "form-control" })
                @*@Html.ValidationMessageFor(model => model.Tareas, "", new { @class = "text-danger" })*@
            </div>

            <div class="form-group col-sm-4">
                <input type="button" value="Agregar" class="btn btn-default" style="margin-top:25px;" onclick="AgregarTarea()" />
            </div>
        </div>

        <div class="form-row">
            <ul class="list-unstyled" id="tareasList">
                @foreach (var tarea in Model.TareasAsignadas)
                {
                    Html.RenderPartial("_Tareas", tarea);
                }
            </ul>
        </div>

        <div class="form-row">
            <div class="form-group col-sm-12">
                @Html.ActionLink("Cancelar", "Index", routeValues: null, htmlAttributes: new { @class = "btn btn-default", @role = "button" })
                <input type="submit" value="Crear" class="btn btn-danger" />
            </div>
        </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    $(document).ready(function () {
        //$('.datepicker').datepicker();
        $('.datepicker').datepicker({
            format: 'mm/dd/yyyy'
        });
    });

    function AgregarTarea() {
        var addTareaURL = '@Url.Action("AgregarTarea", "Plantillas")';
        var tareaTextSelected = $("#tarea_id option:selected").text();
        var tareaValueSelected = $("#tarea_id option:selected").val();

        $.ajax({
            url: addTareaURL + "?tareaId=" + tareaValueSelected + "&tareaTitulo=" + tareaTextSelected,
            cache: false,
            success: function (html) {
                $("#tareasList").append(html);
            },
            error: function (a, b, c) {
                alert("ERROR");
            }
        });
    }

    function RemoverTarea(idTarea) {
        var removeTareaURL = '@Url.Action("RemoverTarea", "Plantillas")';
        $("#hdn-tareaid-" + idTarea).remove();
        $("#li-" + idTarea).remove();
    }
</script>

Presupuestador/Presupuestador/Views/Plantillas/Delete.cshtml
@model Presupuestador.Models.Plantilla

@{
    ViewBag.Title = "Eliminar Plantilla";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar Plantilla</h2>

<h3>Estas seguro que queres eliminar esta plantilla?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nombre
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        @Html.ActionLink("Cancelar", "Index", routeValues: null, htmlAttributes: new { @class = "btn btn-default", @role = "button" })
        <input type="submit" value="Borrar" class="btn btn-danger" />
    </div>
    }
</div>

Presupuestador/Presupuestador/Views/Plantillas/Details.cshtml
@model Presupuestador.Models.Plantilla

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Plantilla</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Presupuestador/Presupuestador/Views/Plantillas/Edit.cshtml
@model Presupuestador.ViewModels.PlantillaViewModel

@{
    ViewBag.Title = "Editar Plantilla";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar Plantilla</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <hr />
    <div class="form-row">
        <div class="form-group col-sm-4">
            @Html.LabelFor(model => model.nombre, "Nombre", htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-sm-4">
            @Html.LabelFor(model => model.tarea_id, "Tareas", new { @class = "control-label" })
            @Html.DropDownList("tarea_id", null, htmlAttributes: new { @class = "form-control" })
            @*@Html.ValidationMessageFor(model => model.Tareas, "", new { @class = "text-danger" })*@
        </div>

        <div class="form-group col-sm-4">
            <input type="button" value="Agregar" class="btn btn-default" style="margin-top:25px;" onclick="AgregarTarea()" />
        </div>
    </div>

    <div class="form-row">
        <ul class="list-unstyled" id="tareasList">
            @foreach (var tarea in Model.TareasAsignadas)
            {
                Html.RenderPartial("_Tareas", tarea);
            }
        </ul>
    </div>

    <div class="form-row">
        <div class="form-group col-sm-12">
            @Html.ActionLink("Cancelar", "Index", routeValues: null, htmlAttributes: new { @class = "btn btn-default", @role = "button" })
            <input type="submit" value="Guardar" class="btn btn-danger" />
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    $(document).ready(function () {
        //$('.datepicker').datepicker();
        $('.datepicker').datepicker({
            format: 'mm/dd/yyyy'
        });
    });

    function AgregarTarea() {
        var addTareaURL = '@Url.Action("AgregarTarea", "Plantillas")';
        var tareaTextSelected = $("#tarea_id option:selected").text();
        var tareaValueSelected = $("#tarea_id option:selected").val();

        $.ajax({
            url: addTareaURL + "?tareaId=" + tareaValueSelected + "&tareaTitulo=" + tareaTextSelected,
            cache: false,
            success: function (html) {
                $("#tareasList").append(html);
            },
            error: function (a, b, c) {
                alert("ERROR");
            }
        });
    }

    function RemoverTarea(idTarea) {
        var removeTareaURL = '@Url.Action("RemoverTarea", "Plantillas")';
        $("#hdn-tareaid-" + idTarea).remove();
        $("#li-" + idTarea).remove();
    }
</script>

Presupuestador/Presupuestador/Views/Plantillas/Index.cshtml
@model IEnumerable<Presupuestador.Models.Plantilla>

@{
    ViewBag.Title = "Plantillas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Plantillas</h2>

<table class="table">
    <tr>
        <th>
            Nombre
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nombre)

        </td>
        <td>
            <span class="glyphicon glyphicon-pencil" data-tooltip="tooltip" data-placement="bottom" title="Editar" onclick="location.href='@Url.Action("Edit", new {id= item.id})'"></span>
            <span class="glyphicon glyphicon-trash" data-tooltip="tooltip" data-placement="bottom" title="Eliminar" onclick="location.href='@Url.Action("Delete", new {id= item.id})'"></span>
        </td>
      </tr>
        }

</table>

<p>
    @Html.ActionLink("Crear Plantilla", "Create", routeValues: null, htmlAttributes: new { @class = "btn btn-danger", @role = "button" })
</p>

Presupuestador/Presupuestador/Views/Plantillas/_Tareas.cshtml
@model Presupuestador.ViewModels.TareaViewModel
@using (Html.BeginCollectionItem("TareasAsignadas"))
{
    <li id="li-@Model.TareaId" class=""><label>Tarea: </label>@Model.Descripcion <span style="cursor:pointer;" class="glyphicon glyphicon-remove" data-tooltip="tooltip" data-placement="bottom" title="Remover" onclick="RemoverTarea(@Model.TareaId)"></span></li>
    @Html.HiddenFor(x => x.TareaId, new { id = "hdn-tareaid-" + Model.TareaId })
    @Html.HiddenFor(x => x.Descripcion, new { id = "hdn-anombre-" + Model.TareaId })
}